### ISSUE TITLE
Tippfehler bei Vorhersage des Alkoholgehalts von Wein

### ISSUE THREAD

**Issue by michael-schindler** [TUD-STKS/tud-ais#2]
Hi, ich hoffe, es stresst nicht allzu hart, wenn ich hier das nebenbei notiere, was ich an Tippfehlern finde

 * [x] l.221: "Dadurch **sind werden** also alle Merkmale in die gleiche Größenordnung gebracht, ohne die relative Verteilung zu vereinfachen."
 * [x] l.375 "Basisfunkti**o**nen"
 * [x] l.409 "und habe**n** eine"
 * [x] l.541 "zu nächst" - wird zusammen geschrieben

Außerdem kann bei den markdown-kursiv-Formatierungen auch `*asterisk*` statt `_underscore_` verwendet werden. Zumindest bei mir wurde `_underscore_` nicht erkannt.

**Comment by nullpunktTUD** [comment]
Stresst überhaupt nicht, ganz im Gegenteil. Das ist genau der richtige Ort dafür! Sammeln Sie ruhig weiter und ich werde mich bei Gelegenheit um die Korrektur kümmern.
